export enum BUYING_FROMAT {
  UNLIMITED_TWO_STAGE = "UNLIMITED_TWO_STAGE",
  STANDART = "STANDART",
  UNLIMITED_WITH_NEGOTIATE = " UNLIMITED_WITH_NEGOTIATE",
  ACQUISITION_UNDER_A_NEGOTIATED_FRAMEWORK_AGREEMENT = "ACQUISITION_UNDER_A_NEGOTIATED_FRAMEWORK_AGREEMENT",
  LIMITED = "LIMITED",
  ADVISORY_SERVICE = "ADVISORY_SERVICE",
}

export enum BUYING_TYPE {
  TOVAR = "TOVAR",
  WORK = "WORK",
  SERVICE = "SERVICE",
}
